### ISSUE TITLE
what

### ISSUE THREAD

**Issue by coldbrewhits** [andreybarsky/nevermore#1]
very nice but why does it say "fuck you oakbrook squad baby" every other hour
![nevermore what](https://user-images.githubusercontent.com/40235792/55443503-d356e780-55aa-11e9-92b1-632432a05ce3.JPG)

**Comment by andreybarsky** [comment]
The only thing I can think of is if the server text corpus is really polluted by this one specific phrase and many, many instances of the word 'fuck' that make it far more likely than any other seed.
If you let me know the name of your server I can check the corpus and find out.

**Comment by andreybarsky** [comment]
Actually I have just confirmed that your channel history contains 495 instances of the exact phrase "fuck you oakbrook squad baby" so the bot has, intelligently, started using it in an attempt to mimic what you guys sound like. 

If you want I can purge your corpus and have the bot start learning your server language model again from scratch.

**Comment by coldbrewhits** [comment]
Ah sure, that'd be helpful

**Comment by andreybarsky** [comment]
Done. It'll take some time to learn again but it should avoid spamming you with that one phrase (until someone else spams the channel with it again).
